# -*- coding: utf-8 -*- 
# SSHFleet 配置文件

# 账号信息
[account]

port = 10022                      # CSV文件默认IP端口 10022
user = "root"                   # CSV文件默认用户名
password = "C:\Users\Administrator\.SSHFleet\mypw"  # 密码文件路径，文件内容为base64编码的密码，支持绝对路径（Windows/Linux）

# 执行参数
[execution]
mode = "sudo"                   # 执行模式，默认值 "direct" or "sudo"
timeout_connect = 10            # 连接超时，连接远程主机的超时，默认值 50秒
timeout_execute = 60            # 执行超时，执行命令或脚本的超时，默认值 60秒
timeout_transfer = 300          # 传输超时，上传或下载文件的超时，默认值 300秒
private_key = "~/.ssh/id_rsa"   # 默认私钥路径， -k 后不输入路径则使用该路径

# 功能开关
[enable]
output_to_xlsx= true             # true：终端内容输出到xlsx文件；false：只输出到txt文件
results_to_xlsx= true           # true：结果固化到xlsx格式的文件；false：不输出到本地文件

# JSON路径
[paths.jsons]
error_keywords="./src/config/error_keywords.json"   # 错误分类关键词JSON文件路径
dangerous_keywords="./src/config/dangerous_keywords.json"   # 危险命令分类正则关键字JSON文件路径

# 程序路径
[paths.exe]
batch_tool_windows = "./src/go/batch_ssh.exe"    # Windows 环境的批量执行程序路径
batch_tool_linux = "./src/go/batch_ssh"          # Linux   环境的批量执行程序路径

# 日志路径
[paths.logs]
zip = ""                        # 打包日志文件生成路径，为空表示在工作路径生成，可用绝对路径
historys = "historys"           # 存放历史记录文件夹名称
tool = "SSHFleetTools.log"      # 工具日志文件名
exec = "msg.log"                # 执行日志文件名

# 结果文件路径
[paths.files]
asset = "assets"                     # 历史记录中转存资产文件夹名称（csv文件、脚本、上传文件，都会备份到这里）
output = "output.txt"                # 终端输出文件名（txt格式）
output_xlsx = "output.xlsx"          # 终端输出文件名（xlsx格式）
report = "report.txt"                # 统计报告文件名
results_xlsx = "results.xlsx"        # 结果固化文件名（xlsx格式）




